name: Continuous Integration

on:
  push:
  pull_request:
    branches: [main]

jobs:
  packaging-tests:
    uses: ./.github/workflows/component_provision_packaging.yml
    secrets:
      AWS_ROLE_ARN: ${{secrets.AWS_ROLE_ARN}}
      AWS_VPC_SUBNET: ${{secrets.AWS_VPC_SUBNET}}
    with:
      BRANCH_REF: "testing_prerelease"
      TAG_OR_UNIQUE_NAME:  "0.0.11"
  check-distributions:
    name: Check distributions name
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check unique distributions names
        run: ./.github/workflows/scripts/check_distro_names.sh
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '~1.19.4'
          check-latest: true

      - name: Verify
        run: make ci
